import Head from "next/head";
import NextLink from "next/link";
import styles from "../styles/Home.module.css";
import { useI18n } from "../hooks/useI18n";
import { useRouter } from "next/router";

export default function Home() {
  const { t } = useI18n();
  const { locales, pathname } = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.description}>
          <p>{t("pages.start")}</p>
        </div>
        <div>
          {locales?.map((locale) => (
            <NextLink key={locale} href={pathname} locale={locale}>
              {locale}
            </NextLink>
          ))}
        </div>
      </main>
    </>
  );
}
